language: python

python:
    - '3.6'

compiler:
    - g++

cache:
    ccache: true
    pip: true

before_install:
  - which pip
  - pip install -q coveralls
  - pip install -q tensorflow
  - pip install -q torch
  - sudo apt-get install gfortran

install:
  - git clone https://github.com/sibirrer/fastell4py.git
  - cd fastell4py
  - python setup.py install
  - cd ..
  - pip install -e . -r requirements.txt
  - df -h

script:
  - coverage run -m unittest discover -s baobab/tests

after_success:
  - codecov
  - coveralls